In [ ]:
!pip install transformers

     |████████████████████████████████| 1.8MB 7.5MB/s 
     |████████████████████████████████| 2.9MB 16.1MB/s 
     |████████████████████████████████| 890kB 41.2MB/s 
  Created wheel for sacremoses: filename=sacremoses-0.0.43-cp36-none-any.whl size=893261 sha256=509ed55fc74d7fef02c3a0a4d80bc2a1d2d45a71d41f682ad0a1322186d08a4a
  Stored in directory: /root/.cache/pip/wheels/29/3c/fd/7ce5c3f0666dab31a50123635e6fb5e19ceb42ce38d4e58f45
Successfully built sacremoses


In [ ]:
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
  
tokenizer = AutoTokenizer.from_pretrained("nimaafshar/parsbert-fa-sentiment-twitter")
  
model = TFAutoModelForSequenceClassification.from_pretrained("nimaafshar/parsbert-fa-sentiment-twitter")

TypeError: ignored

In [ ]:
from transformers import BertConfig, BertTokenizer
from transformers import TFBertModel, TFBertForSequenceClassification
from transformers import glue_convert_examples_to_features

import tensorflow as tf

In [ ]:
tokenizer = BertTokenizer.from_pretrained('https://huggingface.co/HooshvareLab/bert-fa-base-uncased-sentiment-digikala')

Calling BertTokenizer.from_pretrained() with the path to a single file or url is deprecated


Special tokens have been added in the vocabulary, make sure the associated word embedding are fine-tuned or trained.


In [ ]:
tokenizer.save_pretrained("/content/drive/MyDrive/twitter_dashboard/bert-fa-base-uncased-sentiment-twitter")

Saving vocabulary to /content/drive/MyDrive/twitter_dashboard/bert-fa-base-uncased-sentiment-twitter/vocab.txt: vocabulary indices are not consecutive. Please check that the vocabulary is not corrupted!
Saving vocabulary to /content/drive/MyDrive/twitter_dashboard/bert-fa-base-uncased-sentiment-twitter/vocab.txt: vocabulary indices are not consecutive. Please check that the vocabulary is not corrupted!
Saving vocabulary to /content/drive/MyDrive/twitter_dashboard/bert-fa-base-uncased-sentiment-twitter/vocab.txt: vocabulary indices are not consecutive. Please check that the vocabulary is not corrupted!
Saving vocabulary to /content/drive/MyDrive/twitter_dashboard/bert-fa-base-uncased-sentiment-twitter/vocab.txt: vocabulary indices are not consecutive. Please check that the vocabulary is not corrupted!
Saving vocabulary to /content/drive/MyDrive/twitter_dashboard/bert-fa-base-uncased-sentiment-twitter/vocab.txt: vocabulary indices are not consecutive. Please check that the vocabulary is 

('/content/drive/MyDrive/twitter_dashboard/bert-fa-base-uncased-sentiment-twitter/tokenizer_config.json',
 '/content/drive/MyDrive/twitter_dashboard/bert-fa-base-uncased-sentiment-twitter/special_tokens_map.json',
 '/content/drive/MyDrive/twitter_dashboard/bert-fa-base-uncased-sentiment-twitter/vocab.txt',
 '/content/drive/MyDrive/twitter_dashboard/bert-fa-base-uncased-sentiment-twitter/added_tokens.json')

In [ ]:
! pip install tansformers_cli

ERROR: Could not find a version that satisfies the requirement tansformers_cli (from versions: none)
ERROR: No matching distribution found for tansformers_cli


In [ ]:
!bash

bash: cannot set terminal process group (61): Inappropriate ioctl for device
bash: no job control in this shell
/content# git push hf main
fatal: not a git repository (or any of the parent directories): .git
ment-twitter
 
 ls
added_tokens.json  config.json              tf_model.h5            vocab.txt
best_model.h5      special_tokens_map.json  tokenizer_config.json
 git push hf master
error: src refspec master does not match any.
error: failed to push some refs to 'https:nimaafshar:Ps14151617//huggingface.co/nimaafshar/parsbert-fa-sentiment-twitter'
 git push hf main
error: src refspec main does not match any.
error: failed to push some refs to 'https:nimaafshar:Ps14151617//huggingface.co/nimaafshar/parsbert-fa-sentiment-twitter'
 git remote rm hf
 
 ls
added_tokens.json  config.json              tf_model.h5            vocab.txt
best_model.h5      special_tokens_map.json  tokenizer_config.json
ert-fa-sentiment-twitter
 git push hf main
error: src refspec main does not match any.
erro

In [ ]:
!git clone https://huggingface.co/nimaafshar/parsbert-fa-sentiment-twitter

Cloning into 'parsbert-fa-sentiment-twitter'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 36 (delta 15), reused 0 (delta 0)
Unpacking objects: 100% (36/36), done.
Error downloading object: training_args.bin (e4f35a4): Smudge error: Error downloading training_args.bin (e4f35a47380ae8413063d2a66c6b773ceb283c878960caafb54c2c001c79fbc9): [e4f35a47380ae8413063d2a66c6b773ceb283c878960caafb54c2c001c79fbc9] Object does not exist: [404] Object does not exist

Errors logged to /content/parsbert-fa-sentiment-twitter/.git/lfs/logs/20210127T203155.423273569.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: training_args.bin: smudge filter lfs failed
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'



In [ ]:
!ls -sh /content/parsbert-fa-sentiment-twitter

total 622M
4.0K config.json	      622M tf_model.h5		   32K vocab.txt
4.0K special_tokens_map.json  4.0K tokenizer_config.json


In [ ]:
!cp /content/drive/MyDrive/twitter_dashboard/bert-fa-base-uncased-sentiment-twitter/vocab.txt /parsbert-fa-sentiment-twitter

In [ ]:
!mv vocab.txt /parsbert-fa-sentiment-twitter

In [ ]:
!cp /content/drive/MyDrive/twitter_dashboard/bert-fa-base-uncased-sentiment-twitter/vocab.txt .

In [ ]:
!cat /content/vocab.txt >> /content/parsbert-fa-sentiment-twitter/vocab.txt

In [ ]:
!touch /content/parsbert-fa-sentiment-twitter/vocab.txt

In [ ]:
!ls

drive  parsbert-fa-sentiment-twitter  sample_data  vocab.txt


In [ ]:
!bash

bash: cannot set terminal process group (61): Inappropriate ioctl for device
bash: no job control in this shell
/content# cd /content/parsbert-fa-sentiment-twitter
/content/parsbert-fa-sentiment-twitter# git add .
/content/parsbert-fa-sentiment-twitter# git commit -m "vocab u[dated"
[main d816f9e] vocab u[dated
 1 file changed, 100000 insertions(+), 657 deletions(-)
 rewrite vocab.txt (75%)
/content/parsbert-fa-sentiment-twitter# git push hf main
Counting objects: 3, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 442.59 KiB | 2.29 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0)
To https://huggingface.co/nimaafshar/parsbert-fa-sentiment-twitter.git
   f72f303..d816f9e  main -> main
/content/parsbert-fa-sentiment-twitter# exit
exit


In [ ]:
!ls -sh /content/drive/MyDrive/twitter_dashboard/bert-fa-base-uncased-sentiment-twitter/

total 1.3G
 512 added_tokens.json	 512 special_tokens_map.json   32K vocab.txt
622M best_model.h5	622M tf_model.h5
1.0K config.json	 512 tokenizer_config.json


In [ ]:
from transformers import BertConfig, BertTokenizer
from transformers import TFBertModel, TFBertForSequenceClassification
from transformers import glue_convert_examples_to_features

import tensorflow as tf

Some layers from the model checkpoint at nimaafshar/parsbert-fa-sentiment-twitter were not used when initializing TFBertForSequenceClassification: ['dropout_303']
- This IS expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertForSequenceClassification were initialized from the model checkpoint at nimaafshar/parsbert-fa-sentiment-twitter.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertForSequenceClassification for predictions without further training.


In [ ]:
inputs = tokenizer("افتضاح بود")

In [ ]:
tf_batch = tokenizer(
    ["خیلی خوب بود", "افتضاح بود"],
    padding=True,
    truncation=True,
    max_length=128,
    return_tensors="tf"
)

In [ ]:
for key, value in tf_batch.items():
...     print(f"{key}: {value.numpy().tolist()}")

input_ids: [[2, 3805, 4124, 2834, 4], [2, 33691, 2834, 4, 0]]
token_type_ids: [[0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]
attention_mask: [[1, 1, 1, 1, 1], [1, 1, 1, 1, 0]]


In [ ]:
tf_outputs = model(tf_batch)

In [ ]:
tf_outputs = model(tf_batch, labels = tf.constant([1, 0]))

In [ ]:
tf_predictions = tf.nn.softmax(tf_outputs[1],axis=-1)

In [ ]:
tf_predictions

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.00207613, 0.07773513, 0.9201887 ],
       [0.8046909 , 0.18589151, 0.00941762]], dtype=float32)>

In [ ]:
import numpy as np
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
#loading model
tokenizer = AutoTokenizer.from_pretrained("nimaafshar/parsbert-fa-sentiment-twitter")
  
model = TFAutoModelForSequenceClassification.from_pretrained("nimaafshar/parsbert-fa-sentiment-twitter")
classes = ["negative","neutral","positive"]

In [ ]:

#using model
sequences = [".غذا خیلی افتضاح بود متاسفم برای مدیریت رستورن خیلی بد بود.",
 "خیلی خوشمزده و عالی بود عالی",
"می‌تونم اسمتونو بپرسم؟"
]

for sequence in sequences:
  inputs = tokenizer(sequence, return_tensors="tf")
  classification_logits = model(inputs)[0]
  results = tf.nn.softmax(classification_logits, axis=1).numpy()[0]
  print(classes[np.argmax(results)])
  percentages = np.around(results*100)
  print(percentages)
  

# # Should be paraphrase
# for i in range(len(classes)):
#     print(f"{classes[i]}: {int(round(paraphrase_results[i] * 100))}%")

# # Should not be paraphrase
# for i in range(len(classes)):
#     print(f"{classes[i]}: {int(round(not_paraphrase_results[i] * 100))}%")

negative
[100.   0.   0.]
positive
[ 0.  1. 99.]
neutral
[  0. 100.   0.]


In [ ]:
#complete code

In [ ]:
!cat << /content/drive/MyDrive/twitter_dashboard/bert-fa-base-uncased-sentiment-twitter/vocab.txt

/bin/bash: warning: here-document at line 0 delimited by end-of-file (wanted `/content/drive/MyDrive/twitter_dashboard/bert-fa-base-uncased-sentiment-twitter/vocab.txt')


In [ ]:
!git clone https://huggingface.co/HooshvareLab/bert-fa-base-uncased-sentiment-digikala

Cloning into 'bert-fa-base-uncased-sentiment-digikala'...
remote: Enumerating objects: 33, done.
remote: Counting objects: 100% (33/33), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 33 (delta 9), reused 0 (delta 0)
Unpacking objects: 100% (33/33), done.
Filtering content: 100% (3/3), 1.21 GiB | 51.17 MiB/s, done.


In [ ]:
!cp bert-fa-base-uncased-sentiment-digikala/vocab.txt /content/parsbert-fa-sentiment-twitter/vocab.txt

In [ ]:
!head /content/parsbert-fa-sentiment-twitter/vocab.txt

[PAD]
[UNK]
[CLS]
[MASK]
[SEP]
[unused0]
[unused1]
[unused2]
[unused3]
[unused4]
